### ISSUE TITLE
Server-side Render is inconsistent with nil properties

### ISSUE THREAD

**Issue by CmdrDats** [tonsky/rum#104]
So React moans about the checksum failing when hoisting it up.

If the component looks like:

```clojure
[:a {:class (if invariant "found")} "Hello"]
```

Then serverside will render (with `(let [invariant false] ...)` of course):
```html
<a class="">Hello</a>
```

And clientside renders:
```html
<a>Hello</a>
```

**Comment by tonsky** [comment]
What version do you use? I believe I’ve fixed that https://github.com/tonsky/rum/issues/99

**Comment by CmdrDats** [comment]
hmm, I'm using 0.10.7 - seems like the latest?

**Comment by DjebbZ** [comment]
Bumping the issue. I managed to create a minimal reproduction test case that exhibits this exact problem (we have it in our app too). It happens with the `:class` attributes but produces the same problem. Using latest rum 0.10.8, so it still exists.

Here's the repo, with all instructions (pretty simple BTW) : https://github.com/DjebbZ/rum-bug-class

**Comment by DjebbZ** [comment]
Was able to understand a bit more, thank you REPL :

``` clojure
(require '[sablono.core :as s])
;; => nil
(macroexpand '(s/html [:h1 {:class nil} "hello"]))
;; => (js/React.createElement "h1" #js {:className nil} "hello")

(require '[rum.server-render :as rums])
;; => nil
(rums/render-html [:h1 {:class nil} "toto"])
;; => "<h1 data-reactroot=\"\" data-reactid=\"1\" data-react-checksum=\"-1968828468\">toto</h1>"
```

So you can that when rendering client-side (with Sablono), rendering emits that `:class` attributes no matter what, whereas when rendering server-side (with rum), rendering skip that `:class` attribute if it's falsy (tried with `if`, `when`, `false` and `nil`).

I think we should just match the real React behavior.

**Comment by roman01la** [comment]
@CmdrDats @DjebbZ Is this still a thing with `0.11.4`?

**Comment by DjebbZ** [comment]
Hello new maintainer :)

I need to test, will tell you soon.

**Comment by CmdrDats** [comment]
If I do this test in the repl:

```clojure
(let [invariant false] (rums/render-html [:div [:a {:class (if invariant "found")} "Hello"]]))
=> "<div data-reactroot=\"\"><a>Hello</a></div>"
```

Then it looks like this has been resolved. I haven't tested the javascript client side (I'll try remember to do so once I'm in that area of the code again (soonish)), but unless the empty class has been _introduced_ since, it looks like it'll work fine now. Thanks for following up!

**Comment by roman01la** [comment]
@CmdrDats Please get back as soon as you verify this. Thanks.

**Comment by roman01la** [comment]
Ok, checked. React still produces the same result, which means we are fine here. Closing then.
